"""Addition of categories table to the database

Revision ID: 8a97f3fed24e
Revises: dc1f59f7e5bb
Create Date: 2020-05-06 23:49:52.653532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a97f3fed24e'
down_revision = 'dc1f59f7e5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
